class CommandType:
  MOVE_FORWARD = 0
  DRAW_FORWARD = 1
  ROTATE_LEFT = 2
  ROTATE_RIGHT = 3
  PUSH = 4
  POP = 5
  INC_LINE_WIDTH = 6
  DEC_LINE_WIDTH = 7
  DRAW_DOT = 8
  INC_ANGLE = 9
  DEC_ANGLE = 10
  MUL_STEPS = 11
  DIV_STEPS = 12